### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by anil-anand** [anil-anand/neeto-ui-challenge#9]

**Comment by anil-anand** [comment]
Title of issue: Deploy application on Heroku

Deployed at https://neetoui-anil-anand-production.herokuapp.com/
Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink
Please review.

**Comment by yedhink** [comment]
Watch this video: https://www.loom.com/share/2b498a69cdad4f82b023185ba680e6a1

 - [x] Add placeholders
<img width="456" alt="image" src="https://user-images.githubusercontent.com/31244999/193022106-07925599-da0a-48ae-adba-53df2e117ccb.png">

**Comment by anil-anand** [comment]
I am sorry for not finding this during my self-review. The problem was with the `NOTES_FORM_INITIAL_FORM_VALUES` constant. I had forgotten to add the default values for `assignedContact` and `tags`.

I have added placeholders in the forms.

**Comment by yedhink** [comment]
@anil-anand You can mark this task as completed and continue with the next task.
